{
 "title": "qbit",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Torrents size by category",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbit_torrent_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Torrents by category",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbit_torrent_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Torrents by tracker",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbit_torrent_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload/Download speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(qbit_torrent_dlspeed_bytes)",
     "legendFormat": "Download speed"
    },
    {
     "expr": "sum by() (qbit_torrent_upspeed_bytes)",
     "legendFormat": "Upload speed"
    }
   ]
  },
  {
   "title": "Upload/Download bytes total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(qbit_torrent_downloaded_bytes_total)",
     "legendFormat": "Download speed"
    },
    {
     "expr": "sum by() (qbit_torrent_uploaded_bytes_total)",
     "legendFormat": "Upload speed"
    }
   ]
  },
  {
   "title": "Torrent Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "qbit_torrent_info", "legendFormat": "__auto" }
   ]
  }
 ]
}