version: "3.7"

services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  qbit:
    image: lscr.io/linuxserver/qbittorrent
    volumes:
      - ./data:/downloads
    ports:
      - 8080:8080
  qbit-exporter: 
    # image: ghcr.io/janstuemmel/qbit-exporter
    build: ../
    env_file: .env
