name: Build and publish
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  build_publish:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build go binary
        run: CGO_ENABLED=0 go build

      - name: Run unit tests
        run: go test ./... -v

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker build . --tag ghcr.io/janstuemmel/qbit-exporter:latest
          docker push ghcr.io/janstuemmel/qbit-exporter:latest
