name: Build and publish
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  build_publish:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: CGO_ENABLED=0 go build
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build . --tag ghcr.io/janstuemmel/qbit-exporter:latest
          docker push ghcr.io/janstuemmel/qbit-exporter:latest
